version: '3'

services:
  testing_service:
    build: ./
    container_name: API
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
